backend:
  name: github
  repo: glennbrowne8/genes-art-website  # Your actual GitHub username/repo
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # Pages Collection (for Return Policy, etc.)
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  # NEW: Category Management Collection
  - name: "categories"
    label: "Artwork Categories"
    folder: "content/categories"
    create: true
    delete: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - {label: "Category Name", name: "name", widget: "string", hint: "e.g., Corrugated Iron Paintings"}
      - {label: "Description", name: "description", widget: "text", required: false, hint: "Optional: Describe this category of artwork"}
      - {label: "Sort Order", name: "order", widget: "number", default: 0, hint: "Lower numbers appear first (0, 1, 2, etc.)"}
      - {label: "Active", name: "active", widget: "boolean", default: true, hint: "Turn OFF to hide this category without deleting it"}

  - name: "artwork"
    label: "Artwork"
    folder: "content/artwork"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", search_fields: ["name"], value_field: "name", display_fields: ["name"], hint: "Select a category from the list. Add new categories in 'Artwork Categories' section."}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Available", name: "available", widget: "boolean", default: true}
      - {label: "Dimensions", name: "dimensions", widget: "string", required: false}
      - {label: "Weight (kg)", name: "weight", widget: "number", required: false, min: 0, step: 0.1, hint: "Weight in kilograms (e.g., 2.5 or 0.8)"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Stripe Payment Link", name: "stripeLink", widget: "string", required: false, hint: "Paste your Stripe payment link here (e.g., https://buy.stripe.com/...) to enable Buy Now button"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Artist Name", name: "artistName", widget: "string"}
          - {label: "Artist Photo", name: "artistPhoto", widget: "image", required: false, hint: "Upload a photo of the artist (recommended: square image, at least 400x400px)"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "About Text", name: "about", widget: "text"}
          - {label: "Hero Headline", name: "heroHeadline", widget: "string"}
          - {label: "Hero Subtext", name: "heroSubtext", widget: "string"}
          
          - label: "Holiday Mode"
            name: "holidayMode"
            widget: "object"
            collapsed: true
            hint: "Enable this when you're away - shows a friendly message to customers"
            fields:
              - {label: "Enable Holiday Mode", name: "enabled", widget: "boolean", default: false, hint: "Turn ON when going on holidays/leave"}
              - {label: "Return Date (YYYY-MM-DD)", name: "returnDate", widget: "string", required: false, pattern: ['^$|^\\d{4}-\\d{2}-\\d{2}$', 'Must be in format: YYYY-MM-DD (e.g., 2025-12-25) or leave empty'], hint: "Enter date in format: YYYY-MM-DD (e.g., 2025-12-25). Leave empty for 'until further notice'"}
              - {label: "Custom Message", name: "message", widget: "text", required: false, default: "G'day! I'm currently away on leave. The gallery is still here for you to browse, but I'm not taking new orders at the moment.", hint: "Leave empty to use the default message"}
      
      - name: "content"
        label: "Page Content"
        file: "content/settings/page-content.json"
        fields:
          - label: "Contact Page"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Get In Touch"}
              - {label: "Commission Work Heading", name: "commissionHeading", widget: "string", default: "Commission Work"}
              - {label: "Commission Work Text", name: "commissionText", widget: "text", default: "Custom pieces available! I love creating personalized artwork that captures your vision of Australian heritage. Contact me to discuss your ideas."}
              - {label: "Delivery & Shipping Heading", name: "shippingHeading", widget: "string", default: "Delivery & Shipping"}
              - {label: "Delivery & Shipping Text", name: "shippingText", widget: "text", default: "Local delivery available. Interstate shipping can be arranged for all artwork. Contact me for a quote."}
          
          - label: "Gallery Page"
            name: "gallery"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Gallery"}
              - {label: "Empty Gallery Message", name: "emptyMessage", widget: "text", default: "No artwork available yet. Login to the admin panel to add your first piece!"}
          
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "About the Artist"}
          
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Footer Text", name: "text", widget: "string", default: "All rights reserved. | Celebrating Australian culture through authentic artwork"}
